### ISSUE TITLE
Is inshorts.getNews() and inshorts.more() implemented to serve same output?

### ISSUE THREAD

**Issue by nirajKpanda** [ritishgumber/inshorts#2]
Hey Ritish,

I am getting same result for both the implemented functionalities for the bellowed  code.

var is = require('inshorts').init();

is.getNews('sports', function(err, news){
	if (!err){
		const _id = news['id'];
		//parseAndPrettifyNews(news);
		var post_data  = { category : 'sports', id : _id };
        is.more(post_data, function(err, data){
        	if (err)  throw err;
	        else console.log(data);
        });

	}
	else{
		console.log(err)
	}
});

function parseAndPrettifyNews(news){
	console.log(news['headline']);
}

Kindly correct me if any?

Thanks,
Niraj

**Comment by kevindudeja** [comment]
Inshorts fetches 25 news in one go , to see more news of the same category you need to call more function , it will fetch next 25 news from the inshorts.
